"use client";

import { Bot, UserRound, Sparkles } from "lucide-react";
import { useEffect, useRef } from "react";

import { ChatMarkdown } from "@/components/chat/chat-markdown";
import { CitationChips } from "@/components/chat/citation-chips";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Skeleton } from "@/components/ui/skeleton";
import type { ChatMessage, Repository } from "@/lib/api";
import { cn } from "@/lib/utils";

export function ChatMessages({
  repo,
  messages,
  streamText,
  isThinking,
  isLoading,
  onSendSuggestion,
}: {
  repo: Repository;
  messages: ChatMessage[];
  streamText?: string;
  isThinking?: boolean;
  isLoading?: boolean;
  onSendSuggestion?: (content: string) => void | Promise<void>;
}) {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, streamText, isThinking]);

  if (isLoading) {
    return (
      <div className="mx-auto flex w-full max-w-5xl flex-col gap-8 p-8">
        <Skeleton className="h-24 w-3/4 rounded-2xl" />
        <Skeleton className="ml-auto h-16 w-1/2 rounded-2xl" />
        <Skeleton className="h-40 w-5/6 rounded-2xl" />
      </div>
    );
  }

  return (
    <div className="mx-auto flex w-full max-w-5xl flex-col gap-8 px-6 py-8 md:px-10">
      {messages.length === 0 && !streamText && !isThinking && (
        <div className="flex flex-col items-center justify-center rounded-3xl border border-dashed border-border/80 bg-card/60 px-8 py-20 text-center shadow-xs">
          <div className="flex size-14 items-center justify-center rounded-2xl bg-primary/10 text-primary shadow-xs">
            <Sparkles className="size-7" />
          </div>
          <h3 className="mt-5 font-heading text-xl font-semibold tracking-tight text-foreground">
            Ask anything about {repo.fullName}
          </h3>
          <p className="mt-2 max-w-lg text-base text-muted-foreground">
            Codebase answers are grounded using semantic vector search in Qdrant and generated by Google Gemini.
          </p>
          <div className="mt-8 flex flex-wrap justify-center gap-3">
            {[
              "Explain the overall architecture and structure",
              "How is authentication and security implemented?",
              "What are the main database models and routes?",
              "Where are API controllers and handlers located?",
            ].map((suggestion) => (
              <button
                key={suggestion}
                type="button"
                onClick={() => onSendSuggestion?.(suggestion)}
                className="cursor-pointer rounded-xl border border-border/80 bg-muted/60 px-4 py-2.5 text-xs font-medium text-muted-foreground transition-all hover:scale-102 hover:border-primary hover:bg-primary/10 hover:text-primary active:scale-95 shadow-2xs text-left"
              >
                {suggestion} →
              </button>
            ))}
          </div>
        </div>
      )}

      <div className="flex flex-col gap-8">
        {messages.map((message) => {
          const isUser = message.role === "USER";
          return (
            <div
              key={message.id}
              className={cn(
                "flex w-full gap-4 items-start",
                isUser ? "justify-end" : "justify-start"
              )}
            >
              {!isUser && (
                <Avatar className="mt-1 size-10 shrink-0 rounded-2xl border border-border/60 bg-primary/10 text-primary shadow-xs">
                  <AvatarFallback className="bg-transparent font-semibold">
                    <Bot className="size-5 text-primary" />
                  </AvatarFallback>
                </Avatar>
              )}

              <div
                className={cn(
                  "flex flex-col gap-2.5 min-w-0",
                  isUser ? "items-end max-w-[80%]" : "items-start flex-1 max-w-[95%]"
                )}
              >
                <div
                  className={cn(
                    "text-[1rem] leading-relaxed shadow-xs transition-all",
                    isUser
                      ? "rounded-2xl rounded-tr-sm bg-primary px-5 py-3.5 text-primary-foreground font-normal"
                      : "w-full rounded-2xl rounded-tl-sm border border-border/80 bg-card p-6 text-foreground"
                  )}
                >
                  {isUser ? (
                    <span className="whitespace-pre-wrap font-sans text-[0.98rem]">{message.content}</span>
                  ) : (
                    <ChatMarkdown content={message.content} />
                  )}
                </div>

                {!isUser && message.citations && message.citations.length > 0 && (
                  <div className="pt-1 pl-1">
                    <CitationChips repo={repo} citations={message.citations} />
                  </div>
                )}
              </div>

              {isUser && (
                <Avatar className="mt-1 size-10 shrink-0 rounded-2xl border border-border/60 bg-primary text-primary-foreground shadow-xs">
                  <AvatarFallback className="bg-transparent font-semibold">
                    <UserRound className="size-5 text-primary-foreground" />
                  </AvatarFallback>
                </Avatar>
              )}
            </div>
          );
        })}

        {isThinking && (
          <div className="flex w-full items-start justify-start gap-4 animate-in fade-in slide-in-from-bottom-2 duration-300">
            <Avatar className="mt-1 size-10 shrink-0 rounded-2xl border border-border/60 bg-primary/10 text-primary shadow-xs">
              <AvatarFallback className="bg-transparent font-semibold">
                <Bot className="size-5 text-primary animate-pulse" />
              </AvatarFallback>
            </Avatar>

            <div className="flex flex-col gap-2.5 items-start min-w-0">
              <div className="flex items-center gap-3.5 rounded-2xl rounded-tl-sm border border-border/80 bg-card/90 px-6 py-4 text-foreground shadow-xs backdrop-blur-xs">
                <div className="flex items-center gap-1.5">
                  <span className="size-2.5 rounded-full bg-primary animate-bounce [animation-delay:-0.3s]" />
                  <span className="size-2.5 rounded-full bg-primary animate-bounce [animation-delay:-0.15s]" />
                  <span className="size-2.5 rounded-full bg-primary animate-bounce" />
                </div>
                <span className="font-medium text-sm text-foreground/80 tracking-wide">
                  Searching repository & generating answer…
                </span>
              </div>
            </div>
          </div>
        )}

        {streamText && (
          <div className="flex w-full items-start justify-start gap-4">
            <Avatar className="mt-1 size-10 shrink-0 rounded-2xl border border-border/60 bg-primary/10 text-primary shadow-xs">
              <AvatarFallback className="bg-transparent font-semibold">
                <Bot className="size-5 text-primary" />
              </AvatarFallback>
            </Avatar>

            <div className="flex flex-1 max-w-[95%] flex-col gap-2.5 items-start min-w-0">
              <div className="w-full rounded-2xl rounded-tl-sm border border-border/80 bg-card p-6 text-[1rem] leading-relaxed text-foreground shadow-xs">
                <ChatMarkdown content={streamText} isStreaming />
                <span className="ml-1 inline-block h-5 w-2 animate-pulse rounded-xs bg-primary align-middle" />
              </div>
            </div>
          </div>
        )}
      </div>
      <div ref={bottomRef} className="h-6" />
    </div>
  );
}
